### ISSUE TITLE
Crane card -> can't select card to play

### ISSUE THREAD

**Issue by FlashPapa** [ymichael/everdell#48]
On mobile Chrome, The game propose to play some cards with 'crane' (no cost)
But i can't submit ! See the pictures

![signal-2021-06-04-214250_002](https://user-images.githubusercontent.com/2919658/120854837-02e44e80-c57e-11eb-8349-bbb76d884993.jpeg)

![signal-2021-06-04-214250_001](https://user-images.githubusercontent.com/2919658/120854850-05df3f00-c57e-11eb-884d-5dec6b624800.jpeg)

So I changed the season ;)

Thanks, regards

**Comment by FlashPapa** [comment]
Same on Desktop firefox

![Capture d’écran 2021-06-04 à 21 49 52](https://user-images.githubusercontent.com/2919658/120855524-e72d7800-c57e-11eb-8d6f-115713915bf6.png)

![Capture d’écran 2021-06-04 à 21 51 06](https://user-images.githubusercontent.com/2919658/120855627-04fadd00-c57f-11eb-8ffa-9deca403c49f.png)

**Comment by elynnlee** [comment]
@FlashPapa the Crane allows you to discount the cost of a construction by 3 resources (you can mix and match). In order to play the Theatre, you'll still need to pay 2 resources. For example, you could pay 2 wood and use the Crane in place of 1 wood, 1 resin, and 1 stone. Or, you could use the Crane in place of 3 wood, but you'd still need to pay 1 resin and 1 stone.

From your screenshots, it looks like the active player doesn't have any resources. So, they wouldn't be able to play the card, even if they used the Crane. Let me know if you were paying for items correctly and it still didn't work though. Thanks!!

**Comment by FlashPapa** [comment]
You are right, I misread the rule! 
Thanks !
